# Generated by Django 5.2 on 2025-05-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="STT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=100)),
                ("text", models.TextField()),
                ("language", models.CharField(max_length=50)),
                (
                    "duration",
                    models.FloatField(help_text="Duration in seconds"),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_size",
                    models.BigIntegerField(help_text="File size in bytes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("error", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
